version: 2
project_name: stasis

before:
  hooks:
    - go mod tidy
builds:
  - id: stasis
    main: ./cmd/stasis
    binary: stasis
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - formats: ["tar.gz","binary"]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"
changelog:
  use: git
release:
  draft: false
  prerelease: auto
